Fixes by code review
Signed-off-by: Artem Senichev <a.senichev@yadro.com>

diff --git a/admin/led b/admin/led
--- a/admin/led
+++ b/admin/led
@@ -5,7 +5,7 @@
 #
 
 # elevate self privileges
-[[ ${EUID} -ne 0 ]] && exec sudo $(realpath ${BASH_SOURCE[0]}) $@
+[[ ${EUID} -ne 0 ]] && exec /usr/bin/sudo ${BASH_SOURCE[0]} $@
 # prevent modification of executable path
 PATH="/bin:/sbin:/usr/bin:/usr/sbin"
 
@@ -16,8 +16,9 @@ DBUS_INTERFACE="xyz.openbmc_project.Led.Group"
 DBUS_PROPERTY="Asserted"
 
 # parse command line options
-ACTION=
-while [[ $# -gt 0 ]]; do
+if [[ $# -eq 0 ]]; then
+  ACTION="state"
+elif [[ $# -eq 1 ]]; then
   case "$1" in
     -h | --help)
       echo "Chassis LED identify control."
@@ -31,20 +32,17 @@ while [[ $# -gt 0 ]]; do
       exit 0
       ;;
     on | off | state)
-      if [[ -z "${ACTION}" ]]; then
-        ACTION="$1"
-      else
-        echo "Invalid argument, action already defined" >&2
-        exit 1
-      fi
+      ACTION="$1"
       ;;
     *)
       echo "Invalid argument: $1" >&2
       exit 1
       ;;
   esac
-  shift
-done
+else
+  echo "Invalid arguments" >&2
+  exit 1
+fi
 
 # set state
 STATE=
diff --git a/admin/sosreport b/admin/sosreport
--- a/admin/sosreport
+++ b/admin/sosreport
@@ -5,12 +5,12 @@
 #
 
 # elevate self privileges
-[[ ${EUID} -ne 0 ]] && exec sudo $(realpath ${BASH_SOURCE[0]}) $@
+[[ ${EUID} -ne 0 ]] && exec /usr/bin/sudo ${BASH_SOURCE[0]} $@
 # prevent modification of executable path
 PATH="/bin:/sbin:/usr/bin:/usr/sbin"
 
 # parse command line options
-while [[ $# -gt 0 ]]; do
+if [[ $# -eq 1 ]]; then
   case "$1" in
     -h | --help)
       echo "Create system state report."
@@ -24,8 +24,54 @@ while [[ $# -gt 0 ]]; do
       ;;
   esac
   shift
-done
+elif [[ $# -gt 1 ]]; then
+  echo "Invalid arguments" >&2
+  exit 1
+fi
 
-dreport
-echo
-echo "Report created: /tmp/obmcdump_NNNNNNNN_NNNNNNNNNN.tar.xz"
+# Create report over D-Bus call.
+function report_dbus {
+  local mgr_iface="xyz.openbmc_project.Dump.Manager"
+  local mgr_obj="/xyz/openbmc_project/dump"
+  local dump_dir="/var/lib/phosphor-debug-collector/dump"
+
+  echo "Creating SOS report..."
+
+  # remove previous reports
+  busctl call ${mgr_iface} ${mgr_obj} xyz.openbmc_project.Collection.DeleteAll DeleteAll
+  # create new report
+  local entry="$(busctl --list call ${mgr_iface} ${mgr_obj} xyz.openbmc_project.Dump.Create CreateDump)"
+  if [[ -z "${entry}" ]]; then
+    return 1
+  fi
+  # 'u 4' -> '4'
+  entry="${entry##* }"
+  # wait for report complete
+  mapper wait ${mgr_obj}/entry/${entry}
+  # get timestamp to construct file name
+  local elapsed="$(busctl --list get-property ${mgr_iface} \
+                          ${mgr_obj}/entry/${entry} \
+                          xyz.openbmc_project.Time.EpochTime Elapsed)"
+  if [[ -z "${elapsed}" ]]; then
+    return 1
+  fi
+  # 't 1568116858' -> '1568116858'
+  elapsed="${elapsed##* }"
+
+  local filename="/var/lib/phosphor-debug-collector/dumps/obmcdump_${entry}_${elapsed}.tar.xz"
+  if [[ -f ${filename} ]]; then
+    echo "Report created: ${filename}"
+  else
+    return 1
+  fi
+}
+
+# Create report directly with dreport.
+function report_direct {
+  dreport -v
+  echo
+  echo "Report created: /tmp/obmcdump_NNNNNNNN_NNNNNNNNNN.tar.xz"
+}
+
+# try to gather report over D-Bus, if it fails - call dreport directly
+report_dbus || report_direct
